import 'bloc/reset_password_one_bloc.dart';import 'models/reset_password_one_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/core/utils/validation_functions.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application5/widgets/custom_elevated_button.dart';import 'package:basri_s_application5/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class ResetPasswordOneScreen extends StatelessWidget {ResetPasswordOneScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<ResetPasswordOneBloc>(create: (context) => ResetPasswordOneBloc(ResetPasswordOneState(resetPasswordOneModelObj: ResetPasswordOneModel()))..add(ResetPasswordOneInitialEvent()), child: ResetPasswordOneScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 32.v), child: Column(children: [Text("lbl_reset_password".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 17.v), Opacity(opacity: 0.4, child: Container(width: 285.h, margin: EdgeInsets.symmetric(horizontal: 20.h), child: Text("msg_enter_your_new_password".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumOnPrimary14_1.copyWith(height: 1.60)))), SizedBox(height: 51.v), BlocBuilder<ResetPasswordOneBloc, ResetPasswordOneState>(builder: (context, state) {return CustomTextFormField(controller: state.group196Controller, suffix: InkWell(onTap: () {context.read<ResetPasswordOneBloc>().add(ChangePasswordVisibilityEvent(value: !state.isShowPassword));}, child: SizedBox(child: CustomImageView(imagePath: ImageConstant.imgGroup58, height: 52.v, width: 327.h))), suffixConstraints: BoxConstraints(maxHeight: 52.v), obscureText: state.isShowPassword, borderDecoration: TextFormFieldStyleHelper.custom);}), SizedBox(height: 16.v), BlocBuilder<ResetPasswordOneBloc, ResetPasswordOneState>(builder: (context, state) {return CustomTextFormField(controller: state.enusEnvitoController, hintText: "lbl_envito".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, prefix: Container(margin: EdgeInsets.fromLTRB(24.h, 16.v, 11.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgPassword61Onprimary, height: 20.adaptSize, width: 20.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 52.v), suffix: InkWell(onTap: () {context.read<ResetPasswordOneBloc>().add(ChangePasswordVisibilityEvent1(value: !state.isShowPassword1));}, child: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 23.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgEyeOnprimary, height: 24.adaptSize, width: 24.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 52.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: state.isShowPassword1, borderDecoration: TextFormFieldStyleHelper.outlineTeal);}), SizedBox(height: 54.v), CustomElevatedButton(text: "lbl_reset_password".tr), SizedBox(height: 5.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 40.v, leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h, right: 333.h), onTap: () {onTapArrowLeft(context);})); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
