import 'bloc/reset_password_confirmation_bloc.dart';import 'models/reset_password_confirmation_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class ResetPasswordConfirmationScreen extends StatelessWidget {const ResetPasswordConfirmationScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ResetPasswordConfirmationBloc>(create: (context) => ResetPasswordConfirmationBloc(ResetPasswordConfirmationState(resetPasswordConfirmationModelObj: ResetPasswordConfirmationModel()))..add(ResetPasswordConfirmationInitialEvent()), child: ResetPasswordConfirmationScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<ResetPasswordConfirmationBloc, ResetPasswordConfirmationState>(builder: (context, state) {return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 21.h, vertical: 16.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgClose, height: 24.adaptSize, width: 24.adaptSize, onTap: () {onTapImgClose(context);}), SizedBox(height: 21.v), Padding(padding: EdgeInsets.only(left: 127.h), child: Text("lbl_j_bizz".tr, style: theme.textTheme.titleLarge)), SizedBox(height: 92.v), Container(height: 163.v, width: 220.h, margin: EdgeInsets.only(left: 47.h), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgFreepikBackgr, height: 152.v, width: 220.h, alignment: Alignment.topCenter), CustomImageView(imagePath: ImageConstant.imgFreepikPathInject6, height: 9.v, width: 170.h, alignment: Alignment.bottomCenter), CustomImageView(imagePath: ImageConstant.imgFreepikSmartphoneInject6, height: 134.v, width: 74.h, alignment: Alignment.bottomRight, margin: EdgeInsets.only(right: 47.h, bottom: 5.v)), CustomImageView(imagePath: ImageConstant.imgFreepikCharacterInject6, height: 121.v, width: 73.h, alignment: Alignment.bottomLeft, margin: EdgeInsets.only(left: 48.h, bottom: 4.v))])), SizedBox(height: 43.v), Align(alignment: Alignment.center, child: Text("lbl_confirmation".tr, style: theme.textTheme.headlineSmall)), SizedBox(height: 18.v), Align(alignment: Alignment.center, child: Opacity(opacity: 0.4, child: Container(width: 288.h, margin: EdgeInsets.symmetric(horizontal: 22.h), child: Text("msg_your_password_has".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumOnPrimary14_1.copyWith(height: 1.60))))), SizedBox(height: 5.v)])), bottomNavigationBar: _buildLogInButton(context)));}); } 
/// Section Widget
Widget _buildLogInButton(BuildContext context) { return CustomElevatedButton(text: "lbl_log_in".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 61.v)); } 

/// Navigates to the previous screen.
onTapImgClose(BuildContext context) { NavigatorService.goBack(); } 
 }
