import 'bloc/saved_tab_container_bloc.dart';import 'models/saved_tab_container_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/presentation/saved_page/saved_page.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_subtitle_two.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class SavedTabContainerPage extends StatefulWidget {const SavedTabContainerPage({Key? key}) : super(key: key);

@override SavedTabContainerPageState createState() =>  SavedTabContainerPageState();

static Widget builder(BuildContext context) { return BlocProvider<SavedTabContainerBloc>(create: (context) => SavedTabContainerBloc(SavedTabContainerState(savedTabContainerModelObj: SavedTabContainerModel()))..add(SavedTabContainerInitialEvent()), child: SavedTabContainerPage()); } 
 }

// ignore_for_file: must_be_immutable
class SavedTabContainerPageState extends State<SavedTabContainerPage> with  TickerProviderStateMixin {late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 3, vsync: this); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<SavedTabContainerBloc, SavedTabContainerState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 21.v), Padding(padding: EdgeInsets.only(left: 24.h), child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_you".tr, style: theme.textTheme.headlineSmall), TextSpan(text: "msg_saved_48_jobs".tr, style: theme.textTheme.headlineSmall)]), textAlign: TextAlign.left)), SizedBox(height: 37.v), _buildSavedTab(context), SizedBox(height: 511.v, child: TabBarView(controller: tabviewController, children: [SavedPage.builder(context), SavedPage.builder(context), SavedPage.builder(context)]))]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 55.v, leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h, top: 16.v, bottom: 15.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_saved".tr), actions: [Container(height: 49.v, width: 54.h, margin: EdgeInsets.symmetric(horizontal: 18.h, vertical: 3.v), child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: ImageConstant.imgEllipse49x49, height: 49.adaptSize, width: 49.adaptSize, radius: BorderRadius.circular(24.h), alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 5.h)), Align(alignment: Alignment.topRight, child: Container(margin: EdgeInsets.only(left: 38.h, top: 4.v, bottom: 29.v), padding: EdgeInsets.symmetric(horizontal: 3.h, vertical: 4.v), decoration: AppDecoration.bg.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Container(height: 8.adaptSize, width: 8.adaptSize, margin: EdgeInsets.only(right: 2.h), decoration: BoxDecoration(color: appTheme.redA700, borderRadius: BorderRadius.circular(4.h)))))]))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildSavedTab(BuildContext context) { return Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 37.v, width: 288.h, child: TabBar(controller: tabviewController, labelPadding: EdgeInsets.zero, labelColor: theme.colorScheme.onErrorContainer.withOpacity(1), labelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400), unselectedLabelColor: appTheme.gray500, unselectedLabelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400), indicator: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(18.h)), tabs: [Tab(child: Text("lbl_all".tr)), Tab(child: Text("lbl_design".tr)), Tab(child: Text("lbl_developer".tr))])), Container(width: 104.h, margin: EdgeInsets.only(left: 16.h), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 6.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Text("lbl_manager".tr, style: CustomTextStyles.bodyMediumGray50014))]))); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
