import '../search_option_one_screen/widgets/chipview_item_widget.dart';import 'bloc/search_option_one_bloc.dart';import 'models/chipview_item_model.dart';import 'models/search_option_one_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_subtitle_two.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class SearchOptionOneScreen extends StatelessWidget {const SearchOptionOneScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SearchOptionOneBloc>(create: (context) => SearchOptionOneBloc(SearchOptionOneState(searchOptionOneModelObj: SearchOptionOneModel()))..add(SearchOptionOneInitialEvent()), child: SearchOptionOneScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 25.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildSearchRow(context), SizedBox(height: 38.v), Text("lbl_recent_searches".tr, style: theme.textTheme.titleMedium), SizedBox(height: 8.v), Text("msg_you_don_t_have_any".tr, style: CustomTextStyles.bodyMediumGray500_1), SizedBox(height: 39.v), Text("lbl_popular_roles".tr, style: theme.textTheme.titleMedium), SizedBox(height: 12.v), _buildChipView(context), Spacer(), SizedBox(height: 62.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 66.h), child: Text("lbl_j_bizz".tr, style: theme.textTheme.titleLarge)))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 54.v, leadingWidth: 45.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgClose, margin: EdgeInsets.only(left: 21.h, top: 16.v, bottom: 14.v), onTap: () {onTapClose(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_search".tr)); } 
/// Section Widget
Widget _buildSearchRow(BuildContext context) { return Row(children: [Expanded(child: Container(padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 11.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgSearch11Onprimarycontainer, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 3.v)), Container(height: 23.v, width: 174.h, margin: EdgeInsets.only(left: 10.h, top: 3.v), child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.center, child: Text("msg_search_a_job_or".tr, style: CustomTextStyles.bodyMediumGray300)), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 1.h), child: SizedBox(height: 18.v, child: VerticalDivider(width: 2.h, thickness: 2.v, color: appTheme.teal600))))]))]))), Container(height: 52.v, width: 48.h, margin: EdgeInsets.only(left: 16.h), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 12.v), decoration: AppDecoration.outlineOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.circleBorder13), child: CustomImageView(imagePath: ImageConstant.imgFilter5, height: 26.adaptSize, width: 26.adaptSize, alignment: Alignment.center))]); } 
/// Section Widget
Widget _buildChipView(BuildContext context) { return BlocSelector<SearchOptionOneBloc, SearchOptionOneState, SearchOptionOneModel?>(selector: (state) => state.searchOptionOneModelObj, builder: (context, searchOptionOneModelObj) {return Wrap(runSpacing: 12.v, spacing: 12.h, children: List<Widget>.generate(searchOptionOneModelObj?.chipviewItemList.length ?? 0, (index) {ChipviewItemModel model = searchOptionOneModelObj?.chipviewItemList[index] ?? ChipviewItemModel(); return ChipviewItemWidget(model, onSelectedChipView: (value) {context.read<SearchOptionOneBloc>().add(UpdateChipViewEvent(index: index, isSelected: value));});}));}); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
