import '../notifications_page/widgets/usernotification_item_widget.dart';import 'bloc/notifications_bloc.dart';import 'models/notifications_model.dart';import 'models/usernotification_item_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_subtitle_two.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class NotificationsPage extends StatelessWidget {const NotificationsPage({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<NotificationsBloc>(create: (context) => NotificationsBloc(NotificationsState(notificationsModelObj: NotificationsModel()))..add(NotificationsInitialEvent()), child: NotificationsPage()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 8.v), child: Column(children: [SizedBox(height: 7.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_new_activity".tr, style: theme.textTheme.titleSmall)), SizedBox(height: 14.v), _buildNotificationRow1(context), SizedBox(height: 17.v), _buildNotificationRow2(context), SizedBox(height: 30.v), SizedBox(height: 408.v, width: 327.h, child: Stack(alignment: Alignment.bottomCenter, children: [_buildApplicationsColumn(context), _buildInterviewColumn(context)]))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 46.v, leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h, top: 6.v, bottom: 6.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_notifications".tr), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildNotificationRow1(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 8.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 40.adaptSize, width: 40.adaptSize, margin: EdgeInsets.only(bottom: 27.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: CustomImageView(imagePath: ImageConstant.imgImage99, height: 40.adaptSize, width: 40.adaptSize, alignment: Alignment.center)), Expanded(child: Padding(padding: EdgeInsets.only(left: 12.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 266.h, child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_fiverr".tr, style: CustomTextStyles.titleSmallMedium), TextSpan(text: " "), TextSpan(text: "msg_want_to_take_a_final".tr, style: CustomTextStyles.bodyMediumOnPrimary_1)]), textAlign: TextAlign.left)), SizedBox(height: 3.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_12_min_ago".tr, style: CustomTextStyles.labelLarge13), Container(height: 8.adaptSize, width: 8.adaptSize, margin: EdgeInsets.only(left: 6.h, top: 4.v, bottom: 7.v), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(4.h)))])])))])); } 
/// Section Widget
Widget _buildNotificationRow2(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 40.adaptSize, width: 40.adaptSize, margin: EdgeInsets.only(bottom: 27.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: CustomImageView(imagePath: ImageConstant.imgImage97, height: 40.adaptSize, width: 40.adaptSize, radius: BorderRadius.circular(20.h), alignment: Alignment.center)), Expanded(child: Padding(padding: EdgeInsets.only(left: 12.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 275.h, child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_macdonald".tr, style: CustomTextStyles.titleSmallMedium), TextSpan(text: " "), TextSpan(text: "msg_want_to_contact".tr, style: CustomTextStyles.bodyMediumOnPrimary_1)]), textAlign: TextAlign.left)), SizedBox(height: 2.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_47_min_ago".tr, style: CustomTextStyles.labelLarge13), Container(height: 8.adaptSize, width: 8.adaptSize, margin: EdgeInsets.only(left: 6.h, top: 4.v, bottom: 7.v), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(4.h)))])])))]); } 
/// Section Widget
Widget _buildApplicationsColumn(BuildContext context) { return Align(alignment: Alignment.topCenter, child: Column(mainAxisSize: MainAxisSize.min, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_applications".tr, style: theme.textTheme.titleSmall), Text("lbl_see_all".tr, style: CustomTextStyles.bodyMediumGray700_1)]), SizedBox(height: 14.v), Padding(padding: EdgeInsets.only(right: 6.h), child: BlocSelector<NotificationsBloc, NotificationsState, NotificationsModel?>(selector: (state) => state.notificationsModelObj, builder: (context, notificationsModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 13.v);}, itemCount: notificationsModelObj?.usernotificationItemList.length ?? 0, itemBuilder: (context, index) {UsernotificationItemModel model = notificationsModelObj?.usernotificationItemList[index] ?? UsernotificationItemModel(); return UsernotificationItemWidget(model);});})), SizedBox(height: 30.v), Align(alignment: Alignment.centerRight, child: Text("lbl_see_all".tr, style: CustomTextStyles.bodyMediumGray700_1))])); } 
/// Section Widget
Widget _buildInterviewColumn(BuildContext context) { return Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(right: 8.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_interview".tr, style: theme.textTheme.titleSmall), SizedBox(height: 16.v), Row(crossAxisAlignment: CrossAxisAlignment.end, children: [Expanded(child: Container(margin: EdgeInsets.only(bottom: 84.v), padding: EdgeInsets.symmetric(horizontal: 5.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Padding(padding: EdgeInsets.only(right: 4.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 40.adaptSize, width: 40.adaptSize, margin: EdgeInsets.only(bottom: 5.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: CustomImageView(imagePath: ImageConstant.imgImage101, height: 40.adaptSize, width: 40.adaptSize, alignment: Alignment.center)), Expanded(child: Container(width: 266.h, margin: EdgeInsets.only(left: 12.h), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_congratulations2".tr, style: CustomTextStyles.bodyMediumGray500), TextSpan(text: "lbl_beats".tr, style: CustomTextStyles.titleSmallMedium), TextSpan(text: " "), TextSpan(text: "msg_liked_your_resume".tr, style: CustomTextStyles.bodyMediumGray500)]), textAlign: TextAlign.left)))])), SizedBox(height: 2.v), Padding(padding: EdgeInsets.only(left: 52.h), child: Text("lbl_4_hrs_ago".tr, style: CustomTextStyles.labelLargeGray500))]))), Container(height: 40.adaptSize, width: 40.adaptSize, margin: EdgeInsets.only(top: 85.v, bottom: 26.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: CustomImageView(imagePath: ImageConstant.imgImage93, height: 40.adaptSize, width: 40.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(top: 131.v), child: Text("lbl_6_hrs_ago".tr, style: CustomTextStyles.labelLargeGray500)), Expanded(child: Container(width: 253.h, margin: EdgeInsets.only(left: 12.h, top: 84.v, bottom: 22.v), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_congratulations4".tr, style: CustomTextStyles.bodyMediumGray500), TextSpan(text: "lbl_behance".tr, style: CustomTextStyles.titleSmallMedium), TextSpan(text: "msg_be_prepare_for_next".tr, style: CustomTextStyles.bodyMediumGray500)]), textAlign: TextAlign.left)))])]))); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
