import '../resume_portfolio_uploading_screen/widgets/widget_item_widget.dart';import 'bloc/resume_portfolio_uploading_bloc.dart';import 'models/resume_portfolio_uploading_model.dart';import 'models/widget_item_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_subtitle_five.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_subtitle_two.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application5/widgets/custom_elevated_button.dart';import 'package:dotted_border/dotted_border.dart';import 'package:flutter/material.dart';class ResumePortfolioUploadingScreen extends StatelessWidget {const ResumePortfolioUploadingScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ResumePortfolioUploadingBloc>(create: (context) => ResumePortfolioUploadingBloc(ResumePortfolioUploadingState(resumePortfolioUploadingModelObj: ResumePortfolioUploadingModel()))..add(ResumePortfolioUploadingInitialEvent()), child: ResumePortfolioUploadingScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 30.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_resume_or_cv".tr, style: theme.textTheme.titleMedium), SizedBox(height: 22.v), _buildUploadYourCVOr(context), SizedBox(height: 48.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_portfolio2".tr, style: theme.textTheme.titleMedium), TextSpan(text: "lbl_optional".tr, style: CustomTextStyles.bodyLargeOnPrimaryContainer)]), textAlign: TextAlign.left), SizedBox(height: 19.v), _buildWidget(context), SizedBox(height: 9.v)])), bottomNavigationBar: _buildSave(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 36.v, leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h, top: 6.v, bottom: 6.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "msg_resume_portfolio".tr), actions: [AppbarSubtitleFive(text: "lbl_skip".tr, margin: EdgeInsets.fromLTRB(24.h, 8.v, 24.h, 7.v))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildUploadYourCVOr(BuildContext context) { return DottedBorder(color: theme.colorScheme.primary, padding: EdgeInsets.only(left: 1.h, top: 1.v, right: 1.h, bottom: 1.v), strokeWidth: 1.h, radius: Radius.circular(24), borderType: BorderType.RRect, dashPattern: [12, 6], child: Container(padding: EdgeInsets.symmetric(horizontal: 61.h, vertical: 36.v), decoration: AppDecoration.outlinePrimary1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder24), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), SizedBox(width: 201.h, child: Text("msg_upload_your_cv_or".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumGray500_1.copyWith(height: 1.60))), SizedBox(height: 46.v), SizedBox(height: 73.adaptSize, width: 73.adaptSize, child: CircularProgressIndicator(value: 0.5, backgroundColor: theme.colorScheme.primary, color: theme.colorScheme.primary, strokeWidth: 1.h)), SizedBox(height: 50.v), Text("lbl_uploading".tr, style: theme.textTheme.bodyLarge)]))); } 
/// Section Widget
Widget _buildWidget(BuildContext context) { return BlocSelector<ResumePortfolioUploadingBloc, ResumePortfolioUploadingState, ResumePortfolioUploadingModel?>(selector: (state) => state.resumePortfolioUploadingModelObj, builder: (context, resumePortfolioUploadingModelObj) {return Wrap(runSpacing: 15.v, spacing: 15.h, children: List<Widget>.generate(resumePortfolioUploadingModelObj?.widgetItemList.length ?? 0, (index) {WidgetItemModel model = resumePortfolioUploadingModelObj?.widgetItemList[index] ?? WidgetItemModel(); return WidgetItemWidget(model, onSelectedChipView: (value) {context.read<ResumePortfolioUploadingBloc>().add(UpdateChipViewEvent(index: index, isSelected: value));});}));}); } 
/// Section Widget
Widget _buildSave(BuildContext context) { return CustomElevatedButton(text: "lbl_save".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 42.v), buttonStyle: CustomButtonStyles.fillBlueGrayTL5); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
