import 'bloc/job_proposal_tab_container_bloc.dart';import 'models/job_proposal_tab_container_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/presentation/job_proposal_page/job_proposal_page.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_image_one.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_subtitle_one.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class JobProposalTabContainerScreen extends StatefulWidget {const JobProposalTabContainerScreen({Key? key}) : super(key: key);

@override JobProposalTabContainerScreenState createState() =>  JobProposalTabContainerScreenState();

static Widget builder(BuildContext context) { return BlocProvider<JobProposalTabContainerBloc>(create: (context) => JobProposalTabContainerBloc(JobProposalTabContainerState(jobProposalTabContainerModelObj: JobProposalTabContainerModel()))..add(JobProposalTabContainerInitialEvent()), child: JobProposalTabContainerScreen()); } 
 }

// ignore_for_file: must_be_immutable
class JobProposalTabContainerScreenState extends State<JobProposalTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 3, vsync: this); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<JobProposalTabContainerBloc, JobProposalTabContainerState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 25.v), Container(width: 212.h, margin: EdgeInsets.only(left: 24.h), child: Text("msg_you_have_4_job_proposals".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineSmall!.copyWith(height: 1.40))), SizedBox(height: 27.v), _buildTabview(context), SizedBox(height: 553.v, child: TabBarView(controller: tabviewController, children: [JobProposalPage.builder(context), JobProposalPage.builder(context), JobProposalPage.builder(context)]))]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 53.v, centerTitle: true, title: Container(padding: EdgeInsets.symmetric(horizontal: 5.h), decoration: AppDecoration.bg, child: Row(children: [AppbarImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.symmetric(vertical: 13.v), onTap: () {onTapArrowLeft(context);}), AppbarSubtitleOne(text: "lbl_applications".tr, margin: EdgeInsets.only(left: 96.h, top: 13.v, bottom: 12.v)), AppbarImageOne(imagePath: ImageConstant.imgEllipse50x50, margin: EdgeInsets.only(left: 51.h)), Container(margin: EdgeInsets.only(top: 4.v, right: 10.h, bottom: 31.v), padding: EdgeInsets.symmetric(horizontal: 3.h, vertical: 4.v), decoration: AppDecoration.bg.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Container(height: 7.adaptSize, width: 7.adaptSize, margin: EdgeInsets.only(left: 1.h), decoration: BoxDecoration(color: appTheme.redA700, borderRadius: BorderRadius.circular(3.h))))])), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildTabview(BuildContext context) { return Container(height: 37.v, width: 347.h, margin: EdgeInsets.only(right: 4.h), child: TabBar(controller: tabviewController, labelPadding: EdgeInsets.zero, labelColor: theme.colorScheme.onErrorContainer.withOpacity(1), labelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w500), unselectedLabelColor: appTheme.gray500, unselectedLabelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400), indicator: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(18.h)), tabs: [Tab(child: Text("lbl_received".tr)), Tab(child: Text("lbl_answered".tr)), Tab(child: Text("lbl_rejected".tr))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
