import 'bloc/forgot_password_one_tab_container_bloc.dart';import 'models/forgot_password_one_tab_container_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/presentation/forgot_password_three_page/forgot_password_three_page.dart';import 'package:basri_s_application5/presentation/forgot_password_two_page/forgot_password_two_page.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class ForgotPasswordOneTabContainerScreen extends StatefulWidget {const ForgotPasswordOneTabContainerScreen({Key? key}) : super(key: key);

@override ForgotPasswordOneTabContainerScreenState createState() =>  ForgotPasswordOneTabContainerScreenState();

static Widget builder(BuildContext context) { return BlocProvider<ForgotPasswordOneTabContainerBloc>(create: (context) => ForgotPasswordOneTabContainerBloc(ForgotPasswordOneTabContainerState(forgotPasswordOneTabContainerModelObj: ForgotPasswordOneTabContainerModel()))..add(ForgotPasswordOneTabContainerInitialEvent()), child: ForgotPasswordOneTabContainerScreen()); } 
 }

// ignore_for_file: must_be_immutable
class ForgotPasswordOneTabContainerScreenState extends State<ForgotPasswordOneTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 2, vsync: this); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<ForgotPasswordOneTabContainerBloc, ForgotPasswordOneTabContainerState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 8.v), Text("lbl_forgot_password".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 14.v), Opacity(opacity: 0.4, child: Container(width: 285.h, margin: EdgeInsets.only(left: 44.h, right: 45.h), child: Text("msg_enter_your_email".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumOnPrimary14_1.copyWith(height: 1.60)))), SizedBox(height: 54.v), Container(height: 48.v, width: 281.h, decoration: BoxDecoration(color: appTheme.gray100, borderRadius: BorderRadius.circular(16.h)), child: TabBar(controller: tabviewController, labelPadding: EdgeInsets.zero, labelColor: theme.colorScheme.onPrimary.withOpacity(1), labelStyle: TextStyle(fontSize: 13.fSize, fontFamily: 'Circular Std', fontWeight: FontWeight.w400), unselectedLabelColor: theme.colorScheme.onPrimary.withOpacity(1), unselectedLabelStyle: TextStyle(fontSize: 13.fSize, fontFamily: 'Circular Std', fontWeight: FontWeight.w400), indicatorPadding: EdgeInsets.all(6.0.h), indicator: BoxDecoration(color: theme.colorScheme.onErrorContainer.withOpacity(1), borderRadius: BorderRadius.circular(16.h)), tabs: [Tab(child: Text("lbl_e_mail".tr)), Tab(child: Text("lbl_mobile_number".tr))])), SizedBox(height: 495.v, child: TabBarView(controller: tabviewController, children: [ForgotPasswordTwoPage.builder(context), ForgotPasswordThreePage.builder(context)]))]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h, top: 4.v, bottom: 28.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarTitle(text: "lbl_j_bizz".tr)); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
