import '../solo_category_job_listing_screen/widgets/userprofile3_item_widget.dart';import '../solo_category_job_listing_screen/widgets/userprofile4_item_widget.dart';import 'bloc/solo_category_job_listing_bloc.dart';import 'models/solo_category_job_listing_model.dart';import 'models/userprofile3_item_model.dart';import 'models/userprofile4_item_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_subtitle_two.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class SoloCategoryJobListingScreen extends StatelessWidget {const SoloCategoryJobListingScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SoloCategoryJobListingBloc>(create: (context) => SoloCategoryJobListingBloc(SoloCategoryJobListingState(soloCategoryJobListingModelObj: SoloCategoryJobListingModel()))..add(SoloCategoryJobListingInitialEvent()), child: SoloCategoryJobListingScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildArrowLeft(context), Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 22.v), child: Column(children: [_buildFeaturedJobs(context), SizedBox(height: 17.v), _buildUserName(context), SizedBox(height: 30.v), _buildFeaturedJobs1(context), SizedBox(height: 18.v), _buildUserProfile(context)]))])))); } 
/// Section Widget
Widget _buildArrowLeft(BuildContext context) { return Container(padding: EdgeInsets.symmetric(vertical: 16.v), decoration: AppDecoration.outlineSecondaryContainer1, child: Column(mainAxisSize: MainAxisSize.min, children: [CustomAppBar(height: 24.v, leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "msg_ux_designer_jobs".tr)), SizedBox(height: 33.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder16), child: Container(height: 73.v, width: 68.h, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 11.v), decoration: AppDecoration.gradientOrangeToOrange.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Text("lbl_ux".tr, style: CustomTextStyles.headlineSmallBold)), Align(alignment: Alignment.bottomCenter, child: Opacity(opacity: 0.66, child: Padding(padding: EdgeInsets.only(bottom: 2.v), child: Text("lbl_design".tr, style: CustomTextStyles.bodySmallOnPrimary))))]))), Expanded(child: Padding(padding: EdgeInsets.only(left: 16.h), child: Column(children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_437_jobs".tr, style: CustomTextStyles.labelLargePrimary), Text("lbl_86_companies".tr, style: CustomTextStyles.bodyMediumGray500_1)]), SizedBox(height: 9.v), SizedBox(width: 241.h, child: Text("msg_the_ux_designer".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumOnPrimary.copyWith(height: 1.60)))])))])), SizedBox(height: 6.v)])); } 
/// Section Widget
Widget _buildFeaturedJobs(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_featured_jobs".tr, style: theme.textTheme.titleMedium), Padding(padding: EdgeInsets.only(top: 2.v), child: Text("lbl_see_all".tr, style: CustomTextStyles.bodyMediumGray500_1))]); } 
/// Section Widget
Widget _buildUserName(BuildContext context) { return SizedBox(height: 254.v, width: 327.h, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.center, child: BlocSelector<SoloCategoryJobListingBloc, SoloCategoryJobListingState, SoloCategoryJobListingModel?>(selector: (state) => state.soloCategoryJobListingModelObj, builder: (context, soloCategoryJobListingModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: soloCategoryJobListingModelObj?.userprofile3ItemList.length ?? 0, itemBuilder: (context, index) {Userprofile3ItemModel model = soloCategoryJobListingModelObj?.userprofile3ItemList[index] ?? Userprofile3ItemModel(); return Userprofile3ItemWidget(model);});})), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(height: 43.adaptSize, width: 43.adaptSize, decoration: BoxDecoration(image: DecorationImage(image: AssetImage(ImageConstant.imgImage29), fit: BoxFit.cover))), SizedBox(height: 47.v), Container(height: 43.adaptSize, width: 43.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(21.h), image: DecorationImage(image: AssetImage(ImageConstant.imgImage30), fit: BoxFit.cover))), SizedBox(height: 47.v), Container(height: 43.adaptSize, width: 43.adaptSize, decoration: BoxDecoration(image: DecorationImage(image: AssetImage(ImageConstant.imgImage23), fit: BoxFit.cover)))])))])); } 
/// Section Widget
Widget _buildFeaturedJobs1(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_featured_jobs".tr, style: theme.textTheme.titleMedium), Padding(padding: EdgeInsets.only(top: 4.v), child: Text("lbl_see_all".tr, style: CustomTextStyles.bodyMediumGray500_1))]); } 
/// Section Widget
Widget _buildUserProfile(BuildContext context) { return SizedBox(height: 164.v, child: BlocSelector<SoloCategoryJobListingBloc, SoloCategoryJobListingState, SoloCategoryJobListingModel?>(selector: (state) => state.soloCategoryJobListingModelObj, builder: (context, soloCategoryJobListingModelObj) {return ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 15.h);}, itemCount: soloCategoryJobListingModelObj?.userprofile4ItemList.length ?? 0, itemBuilder: (context, index) {Userprofile4ItemModel model = soloCategoryJobListingModelObj?.userprofile4ItemList[index] ?? Userprofile4ItemModel(); return Userprofile4ItemWidget(model);});})); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
