import 'bloc/forgot_password_bloc.dart';import 'models/forgot_password_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application5/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class ForgotPasswordScreen extends StatelessWidget {const ForgotPasswordScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ForgotPasswordBloc>(create: (context) => ForgotPasswordBloc(ForgotPasswordState(forgotPasswordModelObj: ForgotPasswordModel()))..add(ForgotPasswordInitialEvent()), child: ForgotPasswordScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<ForgotPasswordBloc, ForgotPasswordState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 18.v), child: Column(children: [Text("lbl_forgot_password".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 14.v), Opacity(opacity: 0.4, child: Container(width: 285.h, margin: EdgeInsets.symmetric(horizontal: 20.h), child: Text("msg_enter_your_email".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumOnPrimary14_1.copyWith(height: 1.60)))), SizedBox(height: 53.v), Container(margin: EdgeInsets.symmetric(horizontal: 23.h), padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 6.v), decoration: AppDecoration.fillGray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisSize: MainAxisSize.max, children: [CustomElevatedButton(height: 36.v, width: 134.h, text: "lbl_e_mail".tr, buttonStyle: CustomButtonStyles.fillOnErrorContainerTL16, buttonTextStyle: CustomTextStyles.bodyMediumCircularStdOnPrimary), Padding(padding: EdgeInsets.only(left: 20.h, top: 9.v, bottom: 9.v), child: Text("lbl_mobile_number".tr, style: CustomTextStyles.bodyMediumCircularStdOnPrimary))])), SizedBox(height: 40.v), _buildEmailSection(context), SizedBox(height: 32.v), CustomElevatedButton(text: "lbl_send_code".tr), SizedBox(height: 5.v)]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h, top: 14.v, bottom: 17.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarTitle(text: "lbl_j_bizz".tr)); } 
/// Section Widget
Widget _buildEmailSection(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 12.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(children: [Container(height: 12.v, width: 15.h, margin: EdgeInsets.symmetric(vertical: 5.v), child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgVectorOnprimary, height: 12.v, width: 15.h, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgArrowDown, height: 4.v, width: 10.h, alignment: Alignment.topCenter, margin: EdgeInsets.only(top: 2.v))])), Container(height: 21.v, width: 131.h, margin: EdgeInsets.only(left: 13.h, top: 3.v), child: Stack(alignment: Alignment.topRight, children: [Align(alignment: Alignment.center, child: Text("lbl_johnlucas_ux_gm".tr, style: CustomTextStyles.titleSmallMedium_1)), Align(alignment: Alignment.topRight, child: Padding(padding: EdgeInsets.only(right: 38.h), child: SizedBox(height: 18.v, child: VerticalDivider(width: 2.h, thickness: 2.v, color: appTheme.teal600))))]))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
