import 'bloc/profile_style_two_bloc.dart';import 'models/profile_style_two_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_subtitle_three.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class ProfileStyleTwoScreen extends StatelessWidget {const ProfileStyleTwoScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ProfileStyleTwoBloc>(create: (context) => ProfileStyleTwoBloc(ProfileStyleTwoState(profileStyleTwoModelObj: ProfileStyleTwoModel()))..add(ProfileStyleTwoInitialEvent()), child: ProfileStyleTwoScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<ProfileStyleTwoBloc, ProfileStyleTwoState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 8.v), child: Column(children: [Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: appTheme.indigo50, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.circleBorder52), child: Container(height: 104.adaptSize, width: 104.adaptSize, decoration: AppDecoration.fillIndigo.copyWith(borderRadius: BorderRadiusStyle.circleBorder52), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgChristinaWocin104x104, height: 104.adaptSize, width: 104.adaptSize, radius: BorderRadius.circular(52.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgMaskGroupGreen600, height: 104.adaptSize, width: 104.adaptSize, alignment: Alignment.center)]))), SizedBox(height: 10.v), Text("lbl_haley_jessica".tr, style: CustomTextStyles.titleLargeOnPrimary), SizedBox(height: 2.v), Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_ux_designer".tr, style: CustomTextStyles.bodySmallGray500_1), CustomImageView(imagePath: ImageConstant.imgSettings, height: 12.adaptSize, width: 12.adaptSize, margin: EdgeInsets.only(left: 4.h, top: 2.v, bottom: 4.v))]), SizedBox(height: 38.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Column(children: [Text("lbl_27".tr, style: CustomTextStyles.titleMediumCircularStd), SizedBox(height: 6.v), Text("lbl_applied".tr, style: CustomTextStyles.bodySmallGray500_1)]), Spacer(flex: 53), Column(children: [Text("lbl_19".tr, style: CustomTextStyles.titleMediumCircularStd), SizedBox(height: 4.v), Text("lbl_reviewed".tr, style: CustomTextStyles.bodySmallGray500_1)]), Spacer(flex: 46), Column(children: [Text("lbl_14".tr, style: CustomTextStyles.titleMediumCircularStd), SizedBox(height: 4.v), Text("lbl_interview".tr, style: CustomTextStyles.bodySmallGray500_1)])])), SizedBox(height: 37.v), _buildResume(context), SizedBox(height: 10.v), _buildNinetySeven(context), SizedBox(height: 28.v), _buildPortfolio(context), SizedBox(height: 11.v), _buildView(context), SizedBox(height: 8.v)])), bottomNavigationBar: _buildView1(context)));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 24.v, leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h), onTap: () {onTapArrowLeft(context);}), actions: [AppbarSubtitleThree(text: "lbl_edit".tr, margin: EdgeInsets.fromLTRB(24.h, 2.v, 24.h, 3.v))]); } 
/// Section Widget
Widget _buildResume(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_resume".tr, style: theme.textTheme.titleMedium), Padding(padding: EdgeInsets.only(top: 2.v), child: Text("lbl_make_a_resume".tr, style: CustomTextStyles.bodyMediumPrimary))]); } 
/// Section Widget
Widget _buildNinetySeven(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 6.v), decoration: AppDecoration.outlineSecondaryContainer4.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 1.v), Padding(padding: EdgeInsets.only(right: 2.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(width: 32.h, margin: EdgeInsets.only(bottom: 1.v), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 1.v), decoration: AppDecoration.fillBlueA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Text("lbl_cv".tr, style: CustomTextStyles.bodySmallCircularStdOnErrorContainer)), Text("lbl_haley_jessica".tr, style: CustomTextStyles.labelMediumCircularStd), Container(width: 35.h, margin: EdgeInsets.only(bottom: 1.v), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 1.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Text("lbl_pdf".tr, style: CustomTextStyles.bodySmallCircularStdOnErrorContainer))])), SizedBox(height: 1.v), Text("lbl_ux_designer".tr, style: CustomTextStyles.bodySmallCircularStdGray500), SizedBox(height: 8.v), SizedBox(width: 277.h, child: Text("msg_creative_ux_designer2".tr, maxLines: 4, overflow: TextOverflow.ellipsis, style: CustomTextStyles.circularStdGray500))])); } 
/// Section Widget
Widget _buildPortfolio(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_portfolio".tr, style: theme.textTheme.titleMedium), Container(height: 21.v, width: 42.h, margin: EdgeInsets.only(top: 2.v), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topCenter, child: Text("lbl_see_all".tr, style: CustomTextStyles.bodyMediumGray500_1)), Align(alignment: Alignment.center, child: Text("lbl_see_all".tr, style: CustomTextStyles.bodyMediumGray500_1))]))]); } 
/// Section Widget
Widget _buildView(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: appTheme.gray400, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder6), child: Container(height: 98.adaptSize, width: 98.adaptSize, decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgImage12, height: 98.adaptSize, width: 98.adaptSize, radius: BorderRadius.circular(8.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgImage12, height: 98.adaptSize, width: 98.adaptSize, radius: BorderRadius.circular(8.h), alignment: Alignment.center)]))), SizedBox(height: 98.adaptSize, width: 98.adaptSize, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(height: 98.adaptSize, width: 98.adaptSize, decoration: BoxDecoration(color: appTheme.gray400, borderRadius: BorderRadius.circular(8.h)))), CustomImageView(imagePath: ImageConstant.imgImage13, height: 98.adaptSize, width: 98.adaptSize, radius: BorderRadius.circular(8.h), alignment: Alignment.center)])), SizedBox(height: 98.adaptSize, width: 98.adaptSize, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(height: 98.adaptSize, width: 98.adaptSize, decoration: BoxDecoration(color: appTheme.gray400, borderRadius: BorderRadius.circular(8.h)))), CustomImageView(imagePath: ImageConstant.imgImage14, height: 98.adaptSize, width: 98.adaptSize, radius: BorderRadius.circular(8.h), alignment: Alignment.center)]))]); } 
/// Section Widget
Widget _buildView1(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 32.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 98.adaptSize, width: 98.adaptSize, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(height: 98.adaptSize, width: 98.adaptSize, decoration: BoxDecoration(color: appTheme.gray400, borderRadius: BorderRadius.circular(8.h)))), CustomImageView(imagePath: ImageConstant.imgImage15, height: 98.adaptSize, width: 98.adaptSize, radius: BorderRadius.circular(8.h), alignment: Alignment.center)])), Container(height: 98.adaptSize, width: 98.adaptSize, margin: EdgeInsets.only(left: 16.h), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(height: 98.adaptSize, width: 98.adaptSize, decoration: BoxDecoration(color: appTheme.gray400, borderRadius: BorderRadius.circular(8.h)))), CustomImageView(imagePath: ImageConstant.imgImage16, height: 98.adaptSize, width: 98.adaptSize, radius: BorderRadius.circular(8.h), alignment: Alignment.center)])), Container(height: 98.adaptSize, width: 98.adaptSize, margin: EdgeInsets.only(left: 15.h), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(height: 98.adaptSize, width: 98.adaptSize, decoration: BoxDecoration(color: appTheme.gray400, borderRadius: BorderRadius.circular(8.h)))), CustomImageView(imagePath: ImageConstant.imgImage17, height: 98.adaptSize, width: 98.adaptSize, radius: BorderRadius.circular(8.h), alignment: Alignment.center)]))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
