import 'bloc/job_details_three_bloc.dart';import 'models/job_details_three_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application5/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;class JobDetailsThreeScreen extends StatelessWidget {const JobDetailsThreeScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<JobDetailsThreeBloc>(create: (context) => JobDetailsThreeBloc(JobDetailsThreeState(jobDetailsThreeModelObj: JobDetailsThreeModel()))..add(JobDetailsThreeInitialEvent()), child: JobDetailsThreeScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<JobDetailsThreeBloc, JobDetailsThreeState>(builder: (context, state) {return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildMainContent(context), Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 32.v), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), _buildJobDetails(context), SizedBox(height: 20.v), Container(width: 318.h, margin: EdgeInsets.only(right: 8.h), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_we_are_the_teams2".tr, style: CustomTextStyles.bodyMediumCircularStdGray500), TextSpan(text: "msg_responsibilities_full".tr, style: CustomTextStyles.bodyMediumCircularStdGray800.copyWith(height: 1.57))]), textAlign: TextAlign.left))]))])), bottomNavigationBar: _buildApplyButton(context)));}); } 
/// Section Widget
Widget _buildMainContent(BuildContext context) { return Container(decoration: AppDecoration.outlineBlue, child: Container(padding: EdgeInsets.symmetric(vertical: 13.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup60), fit: BoxFit.cover)), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [CustomAppBar(height: 80.v, leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.only(left: 18.h, bottom: 56.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: Container(padding: EdgeInsets.all(20.h), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40), child: AppbarImage(imagePath: ImageConstant.imgFacebook)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgFluentBookmarkAdd20Filled, margin: EdgeInsets.only(left: 23.h, right: 23.h, bottom: 56.v))]), SizedBox(height: 12.v), Text("msg_software_engineer".tr, style: CustomTextStyles.titleLargeCircularStdOnErrorContainer), SizedBox(height: 1.v), Opacity(opacity: 0.75, child: Text("lbl_facebook".tr, style: CustomTextStyles.bodyMediumCircularStdOnErrorContainer)), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(left: 48.h, right: 55.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 69.h, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 3.v), decoration: AppDecoration.fillOnErrorContainer1.copyWith(borderRadius: BorderRadiusStyle.circleBorder13), child: Text("lbl_design".tr, style: CustomTextStyles.bodySmallOnErrorContainer)), Container(width: 82.h, margin: EdgeInsets.only(left: 27.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 4.v), decoration: AppDecoration.fillOnErrorContainer1.copyWith(borderRadius: BorderRadiusStyle.circleBorder13), child: Text("lbl_full_time".tr, style: CustomTextStyles.bodySmallOnErrorContainer)), Container(width: 66.h, margin: EdgeInsets.only(left: 27.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 4.v), decoration: AppDecoration.fillOnErrorContainer1.copyWith(borderRadius: BorderRadiusStyle.circleBorder13), child: Text("lbl_junior".tr, style: CustomTextStyles.bodySmallOnErrorContainer))])), SizedBox(height: 22.v), Padding(padding: EdgeInsets.symmetric(horizontal: 48.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_180_00_year".tr, style: CustomTextStyles.titleMediumOnErrorContainer), Text("lbl_seattle_usa".tr, style: CustomTextStyles.titleMediumOnErrorContainer)])), SizedBox(height: 4.v)]))); } 
/// Section Widget
Widget _buildJobDetails(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_description".tr, style: CustomTextStyles.bodyMediumCircularStdOnPrimary14)), Padding(padding: EdgeInsets.only(left: 28.h, top: 1.v), child: Text("lbl_requirement".tr, style: CustomTextStyles.bodyMediumCircularStdGray50014)), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("lbl_about".tr, style: CustomTextStyles.bodyMediumCircularStdGray50014)), Padding(padding: EdgeInsets.only(left: 28.h), child: Text("lbl_reviews".tr, style: CustomTextStyles.bodyMediumCircularStdGray50014))]); } 
/// Section Widget
Widget _buildApplyButton(BuildContext context) { return CustomElevatedButton(text: "lbl_apply_now".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 34.v)); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
