import 'bloc/apply_bloc.dart';import 'models/apply_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_subtitle_two.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application5/widgets/custom_elevated_button.dart';import 'package:basri_s_application5/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class ApplyScreen extends StatelessWidget {const ApplyScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ApplyBloc>(create: (context) => ApplyBloc(ApplyState(applyModelObj: ApplyModel()))..add(ApplyInitialEvent()), child: ApplyScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildNinetySeven(context), Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 23.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_select_a_profile".tr, style: theme.textTheme.titleMedium), SizedBox(height: 13.v), _buildChristinaWocin(context), SizedBox(height: 30.v), Text("lbl_select_a_resume".tr, style: theme.textTheme.titleMedium), SizedBox(height: 14.v), _buildUxDesigner1(context), SizedBox(height: 40.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_cover_later".tr, style: theme.textTheme.titleMedium), TextSpan(text: "lbl_optional".tr, style: CustomTextStyles.bodyLargeGray500)]), textAlign: TextAlign.left), SizedBox(height: 15.v), _buildCoverLetter1(context), SizedBox(height: 8.v)]))])), bottomNavigationBar: _buildApply(context))); } 
/// Section Widget
Widget _buildNinetySeven(BuildContext context) { return Container(padding: EdgeInsets.symmetric(vertical: 16.v), decoration: AppDecoration.outlineSecondaryContainer1, child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomAppBar(height: 25.v, leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h, bottom: 1.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_apply".tr)), SizedBox(height: 27.v), Padding(padding: EdgeInsets.only(left: 44.h, right: 52.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 44.adaptSize, width: 44.adaptSize, margin: EdgeInsets.only(top: 1.v), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder24), child: CustomImageView(imagePath: ImageConstant.imgImage4, height: 44.adaptSize, width: 44.adaptSize, alignment: Alignment.center)), Expanded(child: Padding(padding: EdgeInsets.only(left: 15.h), child: Column(children: [_buildBurgerKing(context, userLocation: "lbl_ux_intern".tr, userLocationName: "lbl_88_000_y".tr), SizedBox(height: 4.v), _buildBurgerKing(context, userLocation: "lbl_spotify".tr, userLocationName: "lbl_los_angels_us".tr)])))])), SizedBox(height: 4.v)])); } 
/// Section Widget
Widget _buildChristinaWocin(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: theme.colorScheme.onErrorContainer.withOpacity(1), shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder16), child: Container(height: 155.adaptSize, width: 155.adaptSize, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 15.v), decoration: AppDecoration.outlineSecondaryContainer1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Stack(alignment: Alignment.topRight, children: [Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildMask(context), SizedBox(height: 6.v), Text("lbl_haley_jessica".tr, style: CustomTextStyles.titleSmall15), SizedBox(height: 2.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_ux_designer".tr, style: CustomTextStyles.bodySmallGray500), CustomImageView(imagePath: ImageConstant.imgSettings, height: 9.adaptSize, width: 9.adaptSize, margin: EdgeInsets.only(left: 4.h, top: 2.v, bottom: 3.v))])]))), CustomImageView(imagePath: ImageConstant.imgTeenyiconsTickCircleSolid, height: 20.adaptSize, width: 20.adaptSize, alignment: Alignment.topRight)]))), Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 15.v), decoration: AppDecoration.outlineSecondaryContainer1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Column(mainAxisSize: MainAxisSize.min, children: [Align(alignment: Alignment.centerRight, child: SizedBox(height: 105.v, width: 112.h, child: Stack(alignment: Alignment.topRight, children: [Align(alignment: Alignment.centerLeft, child: Column(mainAxisSize: MainAxisSize.min, children: [_buildMask(context), SizedBox(height: 6.v), Text("lbl_haley_jessica".tr, style: CustomTextStyles.titleSmall15)])), Align(alignment: Alignment.topRight, child: Container(height: 20.adaptSize, width: 20.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(10.h), border: Border.all(color: appTheme.blueGray100, width: 1.h))))]))), SizedBox(height: 2.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("msg_product_designer".tr, style: CustomTextStyles.bodySmallGray500), CustomImageView(imagePath: ImageConstant.imgSettings, height: 7.v, width: 8.h, margin: EdgeInsets.only(left: 4.h, top: 3.v, bottom: 3.v))])]))]); } 
/// Section Widget
Widget _buildUxDesigner(BuildContext context) { return CustomElevatedButton(height: 20.v, width: 65.h, text: "lbl_ux_designer".tr, buttonTextStyle: CustomTextStyles.bodySmallCircularStdOnErrorContainer); } 
/// Section Widget
Widget _buildProductDesigner(BuildContext context) { return CustomElevatedButton(height: 20.v, width: 83.h, text: "msg_product_designer".tr, buttonStyle: CustomButtonStyles.fillRed, buttonTextStyle: CustomTextStyles.bodySmallCircularStdOnErrorContainer); } 
/// Section Widget
Widget _buildUxDesigner1(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Container(margin: EdgeInsets.only(right: 8.h), padding: EdgeInsets.symmetric(vertical: 6.v), decoration: AppDecoration.outlineSecondaryContainer1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [CustomImageView(imagePath: ImageConstant.imgTeenyiconsTickCircleSolid, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 12.v)), Padding(padding: EdgeInsets.only(top: 1.v), child: Column(children: [_buildUxDesigner(context), SizedBox(height: 9.v), Text("lbl_haley_jessica".tr, style: CustomTextStyles.labelMediumCircularStd)]))]))), Expanded(child: Container(margin: EdgeInsets.only(left: 8.h), padding: EdgeInsets.symmetric(vertical: 6.v), decoration: AppDecoration.outlineSecondaryContainer1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [Container(height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 12.v), decoration: BoxDecoration(borderRadius: BorderRadius.circular(10.h), border: Border.all(color: appTheme.blueGray100, width: 1.h))), Padding(padding: EdgeInsets.only(top: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildProductDesigner(context), SizedBox(height: 9.v), Text("lbl_haley_jessica".tr, style: CustomTextStyles.labelMediumCircularStd)]))])))]); } 
/// Section Widget
Widget _buildCoverLetter(BuildContext context) { return Expanded(child: BlocSelector<ApplyBloc, ApplyState, TextEditingController?>(selector: (state) => state.coverLetterController, builder: (context, coverLetterController) {return CustomTextFormField(controller: coverLetterController, hintText: "msg_write_a_cover_letter".tr, textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 34.v), borderDecoration: TextFormFieldStyleHelper.outlineSecondaryContainer, filled: true, fillColor: theme.colorScheme.onErrorContainer.withOpacity(1));})); } 
/// Section Widget
Widget _buildCoverLetter1(BuildContext context) { return Row(children: [_buildCoverLetter(context), Container(margin: EdgeInsets.only(left: 16.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 14.v), decoration: AppDecoration.outlineSecondaryContainer1.copyWith(borderRadius: BorderRadiusStyle.circleBorder13), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgBiUpload, height: 16.adaptSize, width: 16.adaptSize), SizedBox(height: 10.v), SizedBox(width: 36.h, child: Text("lbl_upload_pdf".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.labelMediumPrimary.copyWith(height: 1.60)))]))]); } 
/// Section Widget
Widget _buildApply(BuildContext context) { return CustomElevatedButton(text: "lbl_apply".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 34.v)); } 
/// Common widget
Widget _buildBurgerKing(BuildContext context, {required String userLocation, required String userLocationName, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Opacity(opacity: 0.5, child: Text(userLocation, style: theme.textTheme.bodyMedium!.copyWith(color: theme.colorScheme.onPrimary.withOpacity(0.53)))), Opacity(opacity: 0.5, child: Text(userLocationName, style: theme.textTheme.bodyMedium!.copyWith(color: theme.colorScheme.onPrimary.withOpacity(0.53))))]); } 
/// Common widget
Widget _buildMask(BuildContext context) { return Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: appTheme.deepOrange50, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.circleBorder36), child: Container(height: 72.adaptSize, width: 72.adaptSize, decoration: AppDecoration.fillDeepOrange.copyWith(borderRadius: BorderRadiusStyle.circleBorder36), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgChristinaWocin72x72, height: 72.adaptSize, width: 72.adaptSize, radius: BorderRadius.circular(36.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgMaskGroup, height: 72.adaptSize, width: 72.adaptSize, alignment: Alignment.center)]))); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
