import '../companies_screen/widgets/companyprofile_item_widget.dart';import 'bloc/companies_bloc.dart';import 'models/companies_model.dart';import 'models/companyprofile_item_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_subtitle_two.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class CompaniesScreen extends StatelessWidget {const CompaniesScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<CompaniesBloc>(create: (context) => CompaniesBloc(CompaniesState(companiesModelObj: CompaniesModel()))..add(CompaniesInitialEvent()), child: CompaniesScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 40.v), child: Column(children: [_buildComponentFourteen(context), SizedBox(height: 18.v), _buildCompanyProfile(context), SizedBox(height: 55.v), _buildComponentFourteen(context), SizedBox(height: 19.v), _buildSpotify(context, userImage: ImageConstant.imgSpotify2, userName: "lbl_volkswagen".tr, userImage1: ImageConstant.imgSpotify3, userName1: "lbl_burger_king".tr, userImage2: ImageConstant.imgSpotify4, userName2: "lbl_nasa".tr), SizedBox(height: 16.v), _buildSpotify(context, userImage: ImageConstant.imgSpotify5, userName: "lbl_starbucks2".tr, userImage1: ImageConstant.imgSpotify6, userName1: "lbl_bmw".tr, userImage2: ImageConstant.imgSpotify7, userName2: "lbl_firefox".tr), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 46.v, leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h, top: 6.v, bottom: 6.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_companies".tr), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildCompanyProfile(BuildContext context) { return BlocSelector<CompaniesBloc, CompaniesState, CompaniesModel?>(selector: (state) => state.companiesModelObj, builder: (context, companiesModelObj) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 108.v, crossAxisCount: 3, mainAxisSpacing: 16.h, crossAxisSpacing: 16.h), physics: NeverScrollableScrollPhysics(), itemCount: companiesModelObj?.companyprofileItemList.length ?? 0, itemBuilder: (context, index) {CompanyprofileItemModel model = companiesModelObj?.companyprofileItemList[index] ?? CompanyprofileItemModel(); return CompanyprofileItemWidget(model);});}); } 
/// Common widget
Widget _buildComponentFourteen(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_trending_now".tr, style: theme.textTheme.titleMedium), Padding(padding: EdgeInsets.only(top: 2.v), child: Text("lbl_see_all".tr, style: CustomTextStyles.bodyMediumGray500_1))]); } 
/// Common widget
Widget _buildSpotify(BuildContext context, {required String userImage, required String userName, required String userImage1, required String userName1, required String userImage2, required String userName2, }) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Container(margin: EdgeInsets.only(right: 8.h), padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 14.v), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: userImage, height: 44.adaptSize, width: 44.adaptSize, radius: BorderRadius.circular(12.h)), SizedBox(height: 12.v), Text(userName, style: CustomTextStyles.labelLarge13.copyWith(color: theme.colorScheme.onPrimary.withOpacity(1)))]))), Expanded(child: Container(margin: EdgeInsets.symmetric(horizontal: 8.h), padding: EdgeInsets.symmetric(horizontal: 27.h, vertical: 14.v), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: userImage1, height: 44.adaptSize, width: 44.adaptSize, radius: BorderRadius.circular(12.h)), SizedBox(height: 12.v), Text(userName1, style: CustomTextStyles.labelLarge13.copyWith(color: theme.colorScheme.onPrimary.withOpacity(1)))]))), Expanded(child: Container(margin: EdgeInsets.only(left: 8.h), padding: EdgeInsets.symmetric(horizontal: 27.h, vertical: 14.v), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: userImage2, height: 44.adaptSize, width: 44.adaptSize, radius: BorderRadius.circular(12.h)), SizedBox(height: 12.v), Text(userName2, style: CustomTextStyles.labelLarge13.copyWith(color: theme.colorScheme.onPrimary.withOpacity(1)))])))]); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
