import 'bloc/apply_success_two_bloc.dart';import 'models/apply_success_two_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_subtitle_two.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application5/widgets/custom_elevated_button.dart';import 'package:basri_s_application5/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';class ApplySuccessTwoScreen extends StatelessWidget {const ApplySuccessTwoScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ApplySuccessTwoBloc>(create: (context) => ApplySuccessTwoBloc(ApplySuccessTwoState(applySuccessTwoModelObj: ApplySuccessTwoModel()))..add(ApplySuccessTwoInitialEvent()), child: ApplySuccessTwoScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<ApplySuccessTwoBloc, ApplySuccessTwoState>(builder: (context, state) {return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildTwentySix(context), SizedBox(height: 16.v), Container(padding: EdgeInsets.symmetric(horizontal: 24.h), decoration: AppDecoration.outlineSecondaryContainer1, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 267.v, width: 254.h, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Container(height: 162.adaptSize, width: 162.adaptSize, margin: EdgeInsets.only(top: 41.v), decoration: BoxDecoration(color: appTheme.gray5002, borderRadius: BorderRadius.circular(81.h)))), Align(alignment: Alignment.bottomCenter, child: Text("lbl_successful".tr, style: CustomTextStyles.headlineSmallBold)), CustomImageView(imagePath: ImageConstant.imgDoneRafiki1, height: 254.adaptSize, width: 254.adaptSize, alignment: Alignment.topCenter)])), SizedBox(height: 10.v), Container(width: 295.h, margin: EdgeInsets.symmetric(horizontal: 16.h), child: Text("msg_you_ve_successfully2".tr, maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyLargeGray500_1.copyWith(height: 1.50))), SizedBox(height: 84.v), CustomElevatedButton(text: "lbl_track_job".tr), SizedBox(height: 20.v), CustomOutlinedButton(text: "lbl_browse_jobs".tr), SizedBox(height: 5.v)]))]))));}); } 
/// Section Widget
Widget _buildTwentySix(BuildContext context) { return Container(padding: EdgeInsets.symmetric(vertical: 14.v), decoration: AppDecoration.outlineSecondaryContainer1, child: Column(mainAxisSize: MainAxisSize.min, children: [CustomAppBar(height: 25.v, leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h, top: 1.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_confirmation".tr)), SizedBox(height: 28.v), Padding(padding: EdgeInsets.only(left: 44.h, right: 52.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 44.adaptSize, width: 44.adaptSize, margin: EdgeInsets.only(top: 1.v), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder24), child: CustomImageView(imagePath: ImageConstant.imgImage4, height: 44.adaptSize, width: 44.adaptSize, alignment: Alignment.center)), Expanded(child: Padding(padding: EdgeInsets.only(left: 15.h), child: Column(children: [_buildBurgerKing(context, burgerKing: "lbl_ux_intern".tr, losAngelsUS: "lbl_88_000_y".tr), SizedBox(height: 4.v), _buildBurgerKing(context, burgerKing: "lbl_spotify".tr, losAngelsUS: "lbl_los_angels_us".tr)])))])), SizedBox(height: 5.v)])); } 
/// Common widget
Widget _buildBurgerKing(BuildContext context, {required String burgerKing, required String losAngelsUS, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Opacity(opacity: 0.5, child: Text(burgerKing, style: theme.textTheme.bodyMedium!.copyWith(color: theme.colorScheme.onPrimary.withOpacity(0.53)))), Opacity(opacity: 0.5, child: Text(losAngelsUS, style: theme.textTheme.bodyMedium!.copyWith(color: theme.colorScheme.onPrimary.withOpacity(0.53))))]); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
