import 'bloc/profile_style_one_bloc.dart';import 'models/profile_style_one_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_subtitle_three.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class ProfileStyleOneScreen extends StatelessWidget {const ProfileStyleOneScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ProfileStyleOneBloc>(create: (context) => ProfileStyleOneBloc(ProfileStyleOneState(profileStyleOneModelObj: ProfileStyleOneModel()))..add(ProfileStyleOneInitialEvent()), child: ProfileStyleOneScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<ProfileStyleOneBloc, ProfileStyleOneState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 8.v), child: Column(children: [Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: appTheme.indigo50, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.circleBorder52), child: Container(height: 104.adaptSize, width: 104.adaptSize, decoration: AppDecoration.fillIndigo.copyWith(borderRadius: BorderRadiusStyle.circleBorder52), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgChristinaWocin104x104, height: 104.adaptSize, width: 104.adaptSize, radius: BorderRadius.circular(52.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgMaskGroupGreen600, height: 104.adaptSize, width: 104.adaptSize, alignment: Alignment.center)]))), SizedBox(height: 10.v), Text("lbl_haley_jessica".tr, style: CustomTextStyles.titleLargeOnPrimary), SizedBox(height: 2.v), Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_ux_designer".tr, style: CustomTextStyles.bodySmallGray500_1), CustomImageView(imagePath: ImageConstant.imgSettings, height: 12.adaptSize, width: 12.adaptSize, margin: EdgeInsets.only(left: 4.h, top: 2.v, bottom: 4.v))]), SizedBox(height: 38.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Column(children: [Text("lbl_27".tr, style: CustomTextStyles.titleMediumCircularStd), SizedBox(height: 6.v), Text("lbl_applied".tr, style: CustomTextStyles.bodySmallGray500_1)]), Spacer(flex: 53), Column(children: [Text("lbl_19".tr, style: CustomTextStyles.titleMediumCircularStd), SizedBox(height: 4.v), Text("lbl_reviewed".tr, style: CustomTextStyles.bodySmallGray500_1)]), Spacer(flex: 46), Column(children: [Text("lbl_14".tr, style: CustomTextStyles.titleMediumCircularStd), SizedBox(height: 4.v), Text("lbl_interview".tr, style: CustomTextStyles.bodySmallGray500_1)])])), SizedBox(height: 38.v), Padding(padding: EdgeInsets.only(left: 2.h), child: _buildEducation(context, educationLabel: "lbl_experience".tr, seeAllLabel: "lbl_see_all".tr)), SizedBox(height: 9.v), _buildProductManager(context), SizedBox(height: 29.v), Padding(padding: EdgeInsets.only(left: 2.h), child: _buildEducation(context, educationLabel: "lbl_education".tr, seeAllLabel: "lbl_see_all".tr)), SizedBox(height: 11.v), _buildProductManager(context), SizedBox(height: 31.v), _buildResume(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildNinetySeven(context)));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 24.v, leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h), onTap: () {onTapArrowLeft(context);}), actions: [AppbarSubtitleThree(text: "lbl_edit".tr, margin: EdgeInsets.fromLTRB(24.h, 2.v, 24.h, 3.v))]); } 
/// Section Widget
Widget _buildResume(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 2.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_resume".tr, style: theme.textTheme.titleMedium), Padding(padding: EdgeInsets.only(top: 2.v), child: Text("lbl_make_a_resume".tr, style: CustomTextStyles.bodyMediumPrimary))])); } 
/// Section Widget
Widget _buildNinetySeven(BuildContext context) { return Container(margin: EdgeInsets.only(left: 49.h, right: 49.h, bottom: 36.v), decoration: AppDecoration.outlineSecondaryContainer4.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(width: 32.h, margin: EdgeInsets.only(bottom: 1.v), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 1.v), decoration: AppDecoration.fillBlueA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Text("lbl_cv".tr, style: CustomTextStyles.bodySmallCircularStdOnErrorContainer)), Text("lbl_haley_jessica".tr, style: CustomTextStyles.labelMediumCircularStd), Container(width: 35.h, margin: EdgeInsets.only(bottom: 1.v), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 1.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Text("lbl_pdf".tr, style: CustomTextStyles.bodySmallCircularStdOnErrorContainer))]), Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_ux_designer".tr, style: CustomTextStyles.bodySmallCircularStdGray500)), Container(width: 276.h, margin: EdgeInsets.only(top: 8.v), child: Text("msg_creative_ux_designer".tr, maxLines: 4, overflow: TextOverflow.ellipsis, style: CustomTextStyles.circularStdGray500))])); } 
/// Common widget
Widget _buildEducation(BuildContext context, {required String educationLabel, required String seeAllLabel, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(educationLabel, style: theme.textTheme.titleMedium!.copyWith(color: theme.colorScheme.onPrimary.withOpacity(1))), Padding(padding: EdgeInsets.only(top: 3.v), child: Text(seeAllLabel, style: CustomTextStyles.bodyMediumOnPrimaryContainer.copyWith(color: theme.colorScheme.onPrimaryContainer)))]); } 
/// Common widget
Widget _buildProductManager(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 15.v), decoration: AppDecoration.outlineSecondaryContainer1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgImage843x43, height: 43.adaptSize, width: 43.adaptSize, margin: EdgeInsets.only(top: 1.v)), Column(children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_computer_science".tr, style: theme.textTheme.titleSmall), Text("lbl_pasadena".tr, style: theme.textTheme.labelLarge)]), SizedBox(height: 1.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Opacity(opacity: 0.5, child: Text("msg_bachelor_caltech".tr, style: theme.textTheme.bodyMedium)), Opacity(opacity: 0.5, child: Text("lbl_2017_2020".tr, style: theme.textTheme.bodyMedium))])])])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
