import 'bloc/verify_bloc.dart';import 'models/verify_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application5/widgets/custom_elevated_button.dart';import 'package:basri_s_application5/widgets/custom_pin_code_text_field.dart';import 'package:flutter/material.dart';class VerifyScreen extends StatelessWidget {const VerifyScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<VerifyBloc>(create: (context) => VerifyBloc(VerifyState(verifyModelObj: VerifyModel()))..add(VerifyInitialEvent()), child: VerifyScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 9.v), child: Column(children: [Text("lbl_verify_code".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 15.v), Opacity(opacity: 0.4, child: Container(width: 299.h, margin: EdgeInsets.symmetric(horizontal: 13.h), child: Text("msg_enter_your_verification".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumOnPrimary14_1.copyWith(height: 1.60)))), SizedBox(height: 85.v), Padding(padding: EdgeInsets.only(left: 30.h, right: 29.h), child: BlocSelector<VerifyBloc, VerifyState, TextEditingController?>(selector: (state) => state.otpController, builder: (context, otpController) {return CustomPinCodeTextField(context: context, controller: otpController, onChanged: (value) {otpController?.text = value;});})), SizedBox(height: 88.v), CustomElevatedButton(text: "lbl_verify".tr), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h, top: 6.v, bottom: 25.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarTitle(text: "lbl_j_bizz".tr)); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
