import '../solo_company_job_listing_screen/widgets/userprofilelist6_item_widget.dart';import 'bloc/solo_company_job_listing_bloc.dart';import 'models/solo_company_job_listing_model.dart';import 'models/userprofilelist6_item_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_subtitle_two.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;class SoloCompanyJobListingScreen extends StatelessWidget {const SoloCompanyJobListingScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SoloCompanyJobListingBloc>(create: (context) => SoloCompanyJobListingBloc(SoloCompanyJobListingState(soloCompanyJobListingModelObj: SoloCompanyJobListingModel()))..add(SoloCompanyJobListingInitialEvent()), child: SoloCompanyJobListingScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildArrowLeft(context), Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 29.v), child: Column(children: [_buildFeaturedJobsRow1(context), SizedBox(height: 18.v), _buildGoogleRow(context), SizedBox(height: 30.v), _buildFeaturedJobsRow2(context), SizedBox(height: 17.v), _buildUserProfileList(context)]))])))); } 
/// Section Widget
Widget _buildArrowLeft(BuildContext context) { return SizedBox(height: 171.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(vertical: 16.v), decoration: AppDecoration.outlineSecondaryContainer1, child: CustomAppBar(height: 25.v, leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h, bottom: 1.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_google_jobs".tr)))), Align(alignment: Alignment.bottomCenter, child: Container(width: double.maxFinite, margin: EdgeInsets.only(top: 62.v), padding: EdgeInsets.symmetric(vertical: 17.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroupTeal600), fit: BoxFit.cover)), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 19.v, bottom: 6.v), child: Column(children: [Text("lbl_open".tr, style: CustomTextStyles.bodyMediumGray500_1), SizedBox(height: 6.v), Text("lbl_140".tr, style: CustomTextStyles.titleSmall15_1)])), Padding(padding: EdgeInsets.only(bottom: 4.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgGoogle, height: 40.adaptSize, width: 40.adaptSize), SizedBox(height: 7.v), Text("lbl_google".tr, style: CustomTextStyles.titleSmall15_1)])), Padding(padding: EdgeInsets.only(top: 17.v, bottom: 6.v), child: Column(children: [Text("lbl_hired".tr, style: CustomTextStyles.bodyMediumGray500_1), SizedBox(height: 8.v), Text("lbl_176k".tr, style: CustomTextStyles.titleSmall15_1)]))])))])); } 
/// Section Widget
Widget _buildFeaturedJobsRow1(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_featured_jobs".tr, style: theme.textTheme.titleMedium), Padding(padding: EdgeInsets.only(top: 4.v), child: Text("lbl_see_all".tr, style: CustomTextStyles.bodyMediumGray500_1))]); } 
/// Section Widget
Widget _buildGoogleRow(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(right: 7.h), child: _buildFifteen(context, userTitle: "lbl_sr_developer".tr, userCompany: "lbl_google".tr, userSalary: "lbl_115_000_y".tr)), Padding(padding: EdgeInsets.only(left: 7.h), child: _buildFifteen(context, userTitle: "lbl_jr_executive".tr, userCompany: "lbl_google".tr, userSalary: "lbl_96_000_y".tr))]); } 
/// Section Widget
Widget _buildFeaturedJobsRow2(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_featured_jobs".tr, style: theme.textTheme.titleMedium), Padding(padding: EdgeInsets.only(top: 2.v), child: Text("lbl_see_all".tr, style: CustomTextStyles.bodyMediumGray500_1))]); } 
/// Section Widget
Widget _buildUserProfileList(BuildContext context) { return BlocSelector<SoloCompanyJobListingBloc, SoloCompanyJobListingState, SoloCompanyJobListingModel?>(selector: (state) => state.soloCompanyJobListingModelObj, builder: (context, soloCompanyJobListingModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: soloCompanyJobListingModelObj?.userprofilelist6ItemList.length ?? 0, itemBuilder: (context, index) {Userprofilelist6ItemModel model = soloCompanyJobListingModelObj?.userprofilelist6ItemList[index] ?? Userprofilelist6ItemModel(); return Userprofilelist6ItemWidget(model);});}); } 
/// Common widget
Widget _buildFifteen(BuildContext context, {required String userTitle, required String userCompany, required String userSalary, }) { return Expanded(child: SizedBox(width: double.maxFinite, child: Container(padding: EdgeInsets.symmetric(horizontal: 36.h, vertical: 21.v), decoration: AppDecoration.outlineSecondaryContainer1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgGoogle, height: 40.adaptSize, width: 40.adaptSize), SizedBox(height: 10.v), Text(userTitle, style: theme.textTheme.titleSmall!.copyWith(color: theme.colorScheme.onPrimary.withOpacity(1))), SizedBox(height: 4.v), Opacity(opacity: 0.5, child: Text(userCompany, style: CustomTextStyles.bodySmallOnPrimary_1.copyWith(color: theme.colorScheme.onPrimary.withOpacity(0.53)))), SizedBox(height: 6.v), Text(userSalary, style: theme.textTheme.bodySmall!.copyWith(color: theme.colorScheme.onPrimary.withOpacity(1)))])))); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
