import 'bloc/applications_tab_container_bloc.dart';import 'models/applications_tab_container_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/presentation/applications_page/applications_page.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_subtitle_two.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class ApplicationsTabContainerScreen extends StatefulWidget {const ApplicationsTabContainerScreen({Key? key}) : super(key: key);

@override ApplicationsTabContainerScreenState createState() =>  ApplicationsTabContainerScreenState();

static Widget builder(BuildContext context) { return BlocProvider<ApplicationsTabContainerBloc>(create: (context) => ApplicationsTabContainerBloc(ApplicationsTabContainerState(applicationsTabContainerModelObj: ApplicationsTabContainerModel()))..add(ApplicationsTabContainerInitialEvent()), child: ApplicationsTabContainerScreen()); } 
 }

// ignore_for_file: must_be_immutable
class ApplicationsTabContainerScreenState extends State<ApplicationsTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 3, vsync: this); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<ApplicationsTabContainerBloc, ApplicationsTabContainerState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 27.v), Container(width: 211.h, margin: EdgeInsets.only(left: 24.h), child: Text("msg_you_have_27_applications".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineSmall!.copyWith(height: 1.40))), SizedBox(height: 35.v), _buildYouHaveApplications(context), SizedBox(height: 543.v, child: TabBarView(controller: tabviewController, children: [ApplicationsPage.builder(context), ApplicationsPage.builder(context), ApplicationsPage.builder(context)]))]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 53.v, leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h, top: 13.v, bottom: 13.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_applications".tr), actions: [Container(height: 50.v, width: 54.h, margin: EdgeInsets.symmetric(horizontal: 20.h), child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: ImageConstant.imgEllipse50x50, height: 50.adaptSize, width: 50.adaptSize, radius: BorderRadius.circular(25.h), alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 4.h)), Align(alignment: Alignment.topRight, child: Container(margin: EdgeInsets.only(left: 38.h, top: 1.v, bottom: 33.v), padding: EdgeInsets.all(4.h), decoration: AppDecoration.bg.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Container(height: 8.adaptSize, width: 8.adaptSize, decoration: BoxDecoration(color: appTheme.redA700, borderRadius: BorderRadius.circular(4.h)))))]))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildYouHaveApplications(BuildContext context) { return Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 37.v, width: 306.h, child: TabBar(controller: tabviewController, labelPadding: EdgeInsets.zero, labelColor: theme.colorScheme.onErrorContainer.withOpacity(1), labelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400), unselectedLabelColor: appTheme.gray500, unselectedLabelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Poppins', fontWeight: FontWeight.w400), indicator: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(18.h)), tabs: [Tab(child: Text("lbl_all".tr)), Tab(child: Text("lbl_delivered".tr)), Tab(child: Text("lbl_reviewing".tr))])), Container(width: 111.h, margin: EdgeInsets.only(left: 5.h), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 7.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Text("lbl_cancelled".tr, style: CustomTextStyles.bodyMediumGray50014))]))); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
