import 'bloc/job_type_bloc.dart';import 'models/job_type_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application5/widgets/custom_elevated_button.dart';import 'package:basri_s_application5/widgets/custom_radio_button.dart';import 'package:flutter/material.dart';class JobTypeScreen extends StatelessWidget {const JobTypeScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<JobTypeBloc>(create: (context) => JobTypeBloc(JobTypeState(jobTypeModelObj: JobTypeModel()))..add(JobTypeInitialEvent()), child: JobTypeScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.all(24.h), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Container(width: 275.h, margin: EdgeInsets.only(right: 51.h), child: Text("msg_what_type_of_job".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineSmall!.copyWith(height: 1.40)))), SizedBox(height: 43.v), _buildTypeRow(context), SizedBox(height: 16.v), _buildFrameRow(context), SizedBox(height: 16.v), _buildFrameRow1(context), SizedBox(height: 16.v), _buildFrame(context), SizedBox(height: 16.v), _buildFrame(context), SizedBox(height: 16.v), _buildFrameRow3(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildSaveButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 45.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgClose, margin: EdgeInsets.only(left: 21.h, top: 2.v, bottom: 29.v), onTap: () {onTapClose(context);}), centerTitle: true, title: AppbarTitle(text: "lbl_j_bizz".tr)); } 
/// Section Widget
Widget _buildTypeRow(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 31.h, vertical: 11.v), decoration: AppDecoration.outlineGray90005.copyWith(borderRadius: BorderRadiusStyle.circleBorder13), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Opacity(opacity: 0.5, child: CustomImageView(imagePath: ImageConstant.imgCurve1, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))), Expanded(child: BlocSelector<JobTypeBloc, JobTypeState, String?>(selector: (state) => state.radioGroup, builder: (context, radioGroup) {return Padding(padding: EdgeInsets.only(left: 14.h, top: 4.v), child: CustomRadioButton(width: 230.h, text: "lbl_designer".tr, value: "lbl_designer".tr ?? "", groupValue: radioGroup, isRightCheck: true, onChange: (value) {context.read<JobTypeBloc>().add(ChangeRadioButtonEvent(value: value));}));}))])); } 
/// Section Widget
Widget _buildFrameRow(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 31.h, vertical: 11.v), decoration: AppDecoration.outlineGray90005.copyWith(borderRadius: BorderRadiusStyle.circleBorder13), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Opacity(opacity: 0.5, child: CustomImageView(imagePath: ImageConstant.imgCurve120x20, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))), Expanded(child: BlocSelector<JobTypeBloc, JobTypeState, String?>(selector: (state) => state.radioGroup1, builder: (context, radioGroup1) {return Padding(padding: EdgeInsets.only(left: 14.h, top: 4.v), child: CustomRadioButton(width: 230.h, text: "lbl_developer".tr, value: "lbl_developer".tr ?? "", groupValue: radioGroup1, isRightCheck: true, onChange: (value) {context.read<JobTypeBloc>().add(ChangeRadioButton1Event(value: value));}));}))])); } 
/// Section Widget
Widget _buildFrameRow1(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 31.h, vertical: 13.v), decoration: AppDecoration.outlineGray90005.copyWith(borderRadius: BorderRadiusStyle.circleBorder13), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Opacity(opacity: 0.5, child: CustomImageView(imagePath: ImageConstant.imgCurve11, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 2.v))), Expanded(child: BlocSelector<JobTypeBloc, JobTypeState, String?>(selector: (state) => state.radioGroup2, builder: (context, radioGroup2) {return Padding(padding: EdgeInsets.only(left: 14.h), child: CustomRadioButton(width: 230.h, text: "lbl_administrative".tr, value: "lbl_administrative".tr ?? "", groupValue: radioGroup2, isRightCheck: true, onChange: (value) {context.read<JobTypeBloc>().add(ChangeRadioButton2Event(value: value));}));}))])); } 
/// Section Widget
Widget _buildFrameRow3(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 31.h, vertical: 13.v), decoration: AppDecoration.outlineGray90005.copyWith(borderRadius: BorderRadiusStyle.circleBorder13), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Opacity(opacity: 0.5, child: CustomImageView(imagePath: ImageConstant.imgCurve14, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 2.v))), Expanded(child: BlocSelector<JobTypeBloc, JobTypeState, String?>(selector: (state) => state.radioGroup3, builder: (context, radioGroup3) {return Padding(padding: EdgeInsets.only(left: 14.h), child: CustomRadioButton(width: 230.h, text: "lbl_others".tr, value: "lbl_others".tr ?? "", groupValue: radioGroup3, isRightCheck: true, onChange: (value) {context.read<JobTypeBloc>().add(ChangeRadioButton3Event(value: value));}));}))])); } 
/// Section Widget
Widget _buildSaveButton(BuildContext context) { return CustomElevatedButton(text: "lbl_save".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 61.v)); } 
/// Common widget
Widget _buildFrame(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 31.h, vertical: 11.v), decoration: AppDecoration.outlineGray90005.copyWith(borderRadius: BorderRadiusStyle.circleBorder13), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Opacity(opacity: 0.5, child: CustomImageView(imagePath: ImageConstant.imgCurve13, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))), Padding(padding: EdgeInsets.only(left: 14.h, top: 4.v), child: Text("lbl_management".tr, style: theme.textTheme.bodyLarge)), Spacer(), CustomImageView(imagePath: ImageConstant.imgTeenyiconsTickCircleSolid, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
