import 'bloc/job_details_bloc.dart';import 'models/job_details_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application5/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class JobDetailsScreen extends StatelessWidget {const JobDetailsScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<JobDetailsBloc>(create: (context) => JobDetailsBloc(JobDetailsState(jobDetailsModelObj: JobDetailsModel()))..add(JobDetailsInitialEvent()), child: JobDetailsScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<JobDetailsBloc, JobDetailsState>(builder: (context, state) {return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildGreenBackground(context), _buildJobDetails(context)])), bottomNavigationBar: _buildApplyNow(context)));}); } 
/// Section Widget
Widget _buildGreenBackground(BuildContext context) { return SizedBox(height: 281.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgGreenBg, height: 281.v, width: 375.h, alignment: Alignment.center), Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(vertical: 15.v), decoration: BoxDecoration(image: DecorationImage(image: AssetImage(ImageConstant.imgGroup7), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomAppBar(height: 80.v, leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.only(left: 18.h, bottom: 56.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: Container(padding: EdgeInsets.all(20.h), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40), child: AppbarImage(imagePath: ImageConstant.imgGrommetIconsGoogleOnerror40x40)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgFluentBookmarkAdd20Filled, margin: EdgeInsets.only(left: 23.h, right: 23.h, bottom: 56.v))]), SizedBox(height: 12.v), Text("msg_product_designer".tr, style: CustomTextStyles.titleLargeCircularStdOnErrorContainer), SizedBox(height: 2.v), Opacity(opacity: 0.75, child: Text("lbl_google".tr, style: CustomTextStyles.bodyMediumCircularStdOnErrorContainer)), SizedBox(height: 14.v), Padding(padding: EdgeInsets.only(left: 48.h, right: 55.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 69.h, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 3.v), decoration: AppDecoration.fillOnErrorContainer1.copyWith(borderRadius: BorderRadiusStyle.circleBorder13), child: Text("lbl_design".tr, style: CustomTextStyles.bodySmallOnErrorContainer)), Container(width: 82.h, margin: EdgeInsets.only(left: 27.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 4.v), decoration: AppDecoration.fillOnErrorContainer1.copyWith(borderRadius: BorderRadiusStyle.circleBorder13), child: Text("lbl_full_time".tr, style: CustomTextStyles.bodySmallOnErrorContainer)), Container(width: 66.h, margin: EdgeInsets.only(left: 27.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 4.v), decoration: AppDecoration.fillOnErrorContainer1.copyWith(borderRadius: BorderRadiusStyle.circleBorder13), child: Text("lbl_junior".tr, style: CustomTextStyles.bodySmallOnErrorContainer))])), SizedBox(height: 22.v), Padding(padding: EdgeInsets.symmetric(horizontal: 48.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_160_00_year".tr, style: CustomTextStyles.titleMediumOnErrorContainer), Text("lbl_california_usa".tr, style: CustomTextStyles.titleMediumOnErrorContainer)])), SizedBox(height: 20.v)])))])); } 
/// Section Widget
Widget _buildJobDetails(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 6.v), child: Column(mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 9.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_description".tr, style: CustomTextStyles.bodyMediumGray500_1)), Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_requirement".tr, style: CustomTextStyles.bodyMediumOnPrimary)), Text("lbl_about".tr, style: CustomTextStyles.bodyMediumGray500_1), Text("lbl_reviews".tr, style: CustomTextStyles.bodyMediumGray500_1)]), SizedBox(height: 15.v), Container(width: 307.h, margin: EdgeInsets.only(left: 7.h, right: 11.h), child: Text("msg_master_s_degree".tr, maxLines: 15, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumGray50014.copyWith(height: 1.60)))])); } 
/// Section Widget
Widget _buildApplyNow(BuildContext context) { return CustomElevatedButton(text: "lbl_apply_now".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 34.v)); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
