import 'bloc/resume_portfolio_upload_bloc.dart';import 'models/resume_portfolio_upload_model.dart';import 'package:basri_s_application5/core/app_export.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_subtitle_five.dart';import 'package:basri_s_application5/widgets/app_bar/appbar_subtitle_two.dart';import 'package:basri_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application5/widgets/custom_elevated_button.dart';import 'package:dotted_border/dotted_border.dart';import 'package:flutter/material.dart';class ResumePortfolioUploadScreen extends StatelessWidget {const ResumePortfolioUploadScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ResumePortfolioUploadBloc>(create: (context) => ResumePortfolioUploadBloc(ResumePortfolioUploadState(resumePortfolioUploadModelObj: ResumePortfolioUploadModel()))..add(ResumePortfolioUploadInitialEvent()), child: ResumePortfolioUploadScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<ResumePortfolioUploadBloc, ResumePortfolioUploadState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 30.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_resume_or_cv".tr, style: theme.textTheme.titleMedium), SizedBox(height: 22.v), _buildUploadADocDocxPDF(context), SizedBox(height: 48.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_portfolio2".tr, style: theme.textTheme.titleMedium), TextSpan(text: "lbl_optional".tr, style: CustomTextStyles.bodyLargeOnPrimaryContainer)]), textAlign: TextAlign.left), SizedBox(height: 30.v), Padding(padding: EdgeInsets.only(left: 34.h, right: 45.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_portfolio_link".tr, style: CustomTextStyles.titleSmallPrimary), Text("lbl_add_slide".tr, style: CustomTextStyles.titleSmallPrimary)])), SizedBox(height: 35.v), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(left: 49.h, right: 38.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_add_pdf".tr, style: CustomTextStyles.titleSmallPrimary), Text("lbl_add_photos".tr, style: CustomTextStyles.titleSmallPrimary)]))), SizedBox(height: 5.v)])), bottomNavigationBar: _buildSave(context)));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 36.v, leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h, top: 6.v, bottom: 6.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "msg_resume_portfolio".tr), actions: [AppbarSubtitleFive(text: "lbl_skip".tr, margin: EdgeInsets.fromLTRB(24.h, 8.v, 24.h, 7.v))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildUploadADocDocxPDF(BuildContext context) { return DottedBorder(color: theme.colorScheme.primary, padding: EdgeInsets.only(left: 1.h, top: 1.v, right: 1.h, bottom: 1.v), strokeWidth: 1.h, radius: Radius.circular(24), borderType: BorderType.RRect, dashPattern: [12, 6], child: Container(padding: EdgeInsets.symmetric(horizontal: 31.h, vertical: 39.v), decoration: AppDecoration.outlinePrimary1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder24), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 201.h, margin: EdgeInsets.symmetric(horizontal: 30.h), child: Text("msg_upload_your_cv_or".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumGray500_1.copyWith(height: 1.60))), SizedBox(height: 30.v), CustomElevatedButton(height: 73.v, text: "msg_upload_a_doc_docx_pdf".tr, buttonStyle: CustomButtonStyles.fillBlueGrayTL12, buttonTextStyle: CustomTextStyles.titleSmallPrimary), SizedBox(height: 32.v), CustomElevatedButton(width: 184.h, text: "lbl_upload".tr, margin: EdgeInsets.only(left: 30.h), alignment: Alignment.centerLeft)]))); } 
/// Section Widget
Widget _buildSave(BuildContext context) { return CustomElevatedButton(text: "lbl_save".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 42.v), buttonStyle: CustomButtonStyles.fillBlueGrayTL5); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
